
networks:
  proxy_caddy:
    external: true

services:
  backend:
    build:
      dockerfile: Dockerfile
    ports:
     - 8000:8000
    depends_on:
     - redis
    networks:
      - proxy_caddy
  frontend:
    build:
      dockerfile: web.Dockerfile
    ports:
      - 3000:80
    depends_on:
      - backend
    networks:
      - proxy_caddy
  redis:
    image: redis
    networks:
      - proxy_caddy